/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDuUwZaCbLcPN3LvOHdtS0Q",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING")
    }
}).schema({
    "newtable": a.model({
        column1: a.string(),
        id: a.integer().required()
    }).identifier([
        "id"
    ])
});
